version: '3'

services:
  ui:
    container_name: mimsa-ui
    build:
      context: ./ui/.
      dockerfile: ./Dockerfile
      args:
        REACT_APP_MIMSA_API_URL: http://localhost:8999 
        REACT_APP_ROUTER_API_URL: http://localhost:8666
    image: danieljamesharvey/mimsa-ui:local
    ports:
      - '80:80'
    depends_on:
      - api

  api:
    container_name: mimsa-api
    build: ./compiler/.
    image: danieljamesharvey/mimsa-api:local
    ports:
      - '8999:8999'
    environment:
      PORT: 8999
      STORE_ROOT_PATH: /mimsadata
      PROMETHEUS_PORT: 9090
    volumes:
      - ./store_data:/mimsadata

  prometheus:
    container_name: prometheus
    build: ./ops/prometheus/.
    image: danieljamesharvey/mimsa-prometheus:local
    ports:
      - '9090:9090'
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

volumes:
  mimsadata: {}
  prometheus_data: {}
