FROM fpco/stack-build:lts-16.22 as build
RUN mkdir /opt/build
COPY . /opt/build
# deps on a separate layer for re-use
RUN cd /opt/build && stack build --system-ghc --copy-bins --local-bin-path /usr/local/bin

FROM ubuntu:16.04
RUN mkdir -p /opt/myapp
ARG BINARY_PATH
WORKDIR /opt/myapp
RUN apt-get update && apt-get install -y \
  ca-certificates \
  libgmp-dev

# NOTICE THIS LINE
COPY --from=build /usr/local/bin/mimsa . 
CMD ["/opt/myapp/mimsa", "server"]
