name:                mimsa 
version:             0.1.0.0
github:              "danieljharvey/mimsa"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/function-boys#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers
- mtl
- aeson
- text
- hashable
- bytestring
- directory # store
- haskeline # repl
- fsnotify # watch
- brick # tui
- vector # tui
- vty # tui
- microlens # tui
- req # store fetching
- modern-uri # store fetching
- prettyprinter # formatting
- file-embed # js compiling
- megaparsec # parsing

library:
  source-dirs: src

executables:
  mimsa:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mimsa

tests:
  mimsa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mimsa
    - hspec
    - QuickCheck
    - generic-arbitrary
    - quickcheck-instances
