name:                mimsa 
version:             0.1.0.0
github:              "danieljharvey/mimsa"
license:             BSD3
author:              "Daniel J Harvey"
maintainer:          "danieljamesharvey@gmail.com"
copyright:           "2021 Daniel J Harvey"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/function-boys#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers
- mtl
- aeson
- text
- servant # server
- servant-server # server
- cryptonite # hashing
- memory # hashing
- file-embed # js stdlib
- bytestring
- directory # store
- prettyprinter # formatting
- megaparsec # parsing
- parser-combinators # parsing
- monad-logger # logging
- zip-archive # downloads
- binary # downloads
- hashable
- QuickCheck # properties
- exceptions 
- openapi3 

library:
  source-dirs: src

executables:
  mimsa:
    main:                Main.hs
    source-dirs:         repl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mimsa
    - haskeline # repl
    - optparse-applicative # cli

  mimsa-server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-T
    dependencies:
    - mimsa
    - optparse-applicative # cli
    - wai # server
    - warp # server
    - wai-cors # server
    - http-types # server
    - servant-openapi3 # server
    - envy # server
    - stm # concurrency for server
    - wai-middleware-prometheus # metrics
    - prometheus-client # metrics
    - prometheus-metrics-ghc # metrics

tests:
  mimsa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mimsa
    - hspec
    - typed-process

benchmarks:
  mimsa-benchmark:
    main:                Spec.hs
    source-dirs:         benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mimsa
    - criterion
