name:                mimsa 
version:             0.1.0.0
github:              "danieljharvey/mimsa"
license:             BSD3
author:              "Daniel J Harvey"
maintainer:          "danieljamesharvey@gmail.com"
copyright:           "2021 Daniel J Harvey"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/function-boys#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers
- mtl
- aeson
- text
- cryptonite # hashing
- memory # hashing
- bytestring
- directory # store
- haskeline # repl
- exceptions # repl
- prettyprinter # formatting
- megaparsec # parsing
- parser-combinators # parsing
- servant # server
- servant-server # server
- wai # server
- warp # server
- wai-cors # server
- http-types # server
- optparse-applicative # cli
- servant-openapi3 # server
- openapi3 # server
- envy # server
- stm # concurrency for server
- monad-logger # logging
- zip-archive # downloads
- binary # downloads
- hashable
- QuickCheck # properties

library:
  source-dirs: src
  default-extensions:
    - Strict 

executables:
  mimsa:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mimsa

  swagger:
    main:                Main.hs
    source-dirs:         swagger
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mimsa

tests:
  mimsa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mimsa
    - hspec
    - typed-process
