name: Compiler - build

on:
  push:
    branches:
      - trunk
    paths:
      - "compiler/**"
      - "server/**"
      - "repl/**"
      - "core/**"
      - "backends/**"

  pull_request:
    branches:
      - trunk
    paths:
      - "compiler/**"
      - "server/**"
      - "repl/**"
      - "core/**"
      - "backends/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache cabal global package db
        id: cabal-global
        uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-1-cabal-global-${{ matrix.plan.ghc }}-${{ hashFiles('**.freeze') }}
          restore-keys: |
            ${{ runner.os }}-1-cabal-global-${{ matrix.plan.ghc }}

      - name: Cache cabal-installed programs in ~/.local/bin
        id: cabal-programs
        uses: actions/cache@v3
        with:
          path: ~/.cabal/bin
          key: ${{ runner.os }}-1-cabal-programs-${{ matrix.plan.ghc }}-${{ hashFiles('**.freeze') }}
          restore-keys: |
            ${{ runner.os }}-1-cabal-programs-${{ matrix.plan.ghc }}

      - name: Cache .cabal-work
        uses: actions/cache@v3
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-1-cabal-work-${{ matrix.plan.ghc }}-${{ hashFiles('**.freeze') }}
          restore-keys: |
            ${{ runner.os }}-1-cabal-work-${{ matrix.plan.ghc }}

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2.5'
          cabal-version: '3.8.1.0'

      - name: Test core
        run: make test-core

      - name: Test backends
        run: make test-backends

      - name: Test compiler
        run: yarn global add typescript@4.4 ts-node@10.4.0 & make test

      - name: Build all things
        run: make build

      - name: Run benchmarks
        run: make bench

      - name: Generate swagger json
        run: make generate-swagger
