name: Compiler - build

on:
  push:
    branches:
      - trunk
    paths:
      - "compiler/**"

  pull_request:
    branches:
      - trunk
    paths:
      - "compiler/**"

jobs:
  ormolu:
    env:
      working-directory: compiler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v7

  build:
    needs: ormolu
    env:
      working-directory: compiler
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache cabal global package db
        id: cabal-global
        uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-1-cabal-global-${{ matrix.plan.ghc }}-${{ hashFiles('**.freeze') }}
          restore-keys: |
            ${{ runner.os }}-1-cabal-global-${{ matrix.plan.ghc }}

      - name: Cache cabal-installed programs in ~/.local/bin
        id: cabal-programs
        uses: actions/cache@v3
        with:
          path: ~/.cabal/bin
          key: ${{ runner.os }}-1-cabal-programs-${{ matrix.plan.ghc }}-${{ hashFiles('**.freeze') }}
          restore-keys: |
            ${{ runner.os }}-1-cabal-programs-${{ matrix.plan.ghc }}

      - name: Cache .cabal-work
        uses: actions/cache@v3
        with:
          path: compiler/dist-newstyle
          key: ${{ runner.os }}-1-cabal-work-${{ matrix.plan.ghc }}-${{ hashFiles('**.freeze') }}
          restore-keys: |
            ${{ runner.os }}-1-cabal-work-${{ matrix.plan.ghc }}

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.4.3'
          cabal-version: '3.8.1.0'

      - name: "Set up HLint"
        uses: rwe/actions-hlint-setup@v1
        with:
          version: "3.1.6"

      - name: "Run HLint"
        uses: rwe/actions-hlint-run@v2
        with:
          path: compiler/src/
          fail-on: warning

      - name: cabal update
        run: cd compiler && cabal update

      - name: Run cabal test
        run: yarn global add typescript@4.4 ts-node@10.4.0 & cd compiler && make test

      - name: Run cabal build
        run: cd compiler && make build 

      - name: Run cabal bench
        run: cd compiler && make bench 

      - name: Generate swagger json
        run: cd compiler && make install && $(cabal list-bin mimsa-server) generate-swagger
