name: Compiler - build

on:
  push:
    branches:
      - trunk
    paths:
      - "compiler/**"
      - "server/**"

  pull_request:
    branches:
      - trunk
    paths:
      - "compiler/**"
      - "server/**"

jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v8

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Set up HLint"
        uses: rwe/actions-hlint-setup@v1
        with:
          version: "3.1.6"

      - name: "Run HLint"
        uses: rwe/actions-hlint-run@v2
        with:
          path: compiler/src/
          fail-on: warning

  build:
    needs:
      - ormolu
      - hlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache cabal global package db
        id: cabal-global
        uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-1-cabal-global-${{ matrix.plan.ghc }}-${{ hashFiles('**.freeze') }}
          restore-keys: |
            ${{ runner.os }}-1-cabal-global-${{ matrix.plan.ghc }}

      - name: Cache cabal-installed programs in ~/.local/bin
        id: cabal-programs
        uses: actions/cache@v3
        with:
          path: ~/.cabal/bin
          key: ${{ runner.os }}-1-cabal-programs-${{ matrix.plan.ghc }}-${{ hashFiles('**.freeze') }}
          restore-keys: |
            ${{ runner.os }}-1-cabal-programs-${{ matrix.plan.ghc }}

      - name: Cache .cabal-work
        uses: actions/cache@v3
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-1-cabal-work-${{ matrix.plan.ghc }}-${{ hashFiles('**.freeze') }}
          restore-keys: |
            ${{ runner.os }}-1-cabal-work-${{ matrix.plan.ghc }}

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2.5'
          cabal-version: '3.8.1.0'

      - name: Run cabal test
        run: yarn global add typescript@4.4 ts-node@10.4.0 & make test

      - name: Run cabal build
        run: make build

      - name: Run cabal bench
        run: make bench

      - name: Generate swagger json
        run: make generate-swagger
