name: Docker build

on:
  push:
    branches:
      - trunk
    paths:
      - "compiler/**"

jobs:
  build:
    env:
      working-directory: ./compiler
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
   
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        tags: danieljamesharvey/mimsa-api:latest
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Update Docker Compose 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: ./deploy-mimsa.sh
